name:                nctumpc
version:             0.1.0.0
github:              "abt8601/nctumpc"
license:             Unlicense
author:              "Po-Yi Tsai"
maintainer:          "abt8601@protonmail.ch"
copyright:           "2021 Po-Yi Tsai"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/abt8601/nctumpc#readme>

dependencies:
- array >= 0.5 && < 0.6
- base >= 4.7 && < 5
- bytestring >= 0.10 && < 0.11
- mtl >= 2 && < 3
- text >= 1 && < 2

library:
  source-dirs: src

executables:
  nctumpc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nctumpc

  icd-hw1-test-exe:
    main:                Main.hs
    source-dirs:         icd-test-exes/hw1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nctumpc

tests:
  nctumpc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nctumpc

  icd-hw1-test:
    main:                Main.hs
    source-dirs:         icd-test/hw1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nctumpc
    - process >= 1 && < 2
